import turtle
turtle.pensize(2)
turtle.pencolor("red")
turtle.fillcolor("red")
turtle.speed(10)
turtle.begin_fill()
turtle.left(45)
turtle.forward(100)
turtle.circle(50,180)
turtle.right(90)
turtle.circle(50,180)
turtle.forward(100)
turtle.end_fill()
turtle.hideturtle()
turtle.done()